name: Build and Deploy Python Flask App with Helm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: acrk8sdemoappdev.azurecr.io
  IMAGE_NAME: images

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve secrets from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        id: keyvault
        with:
          keyvault: kv-k8s-demo-app-dev
          secrets: 'acrAdminName, acrAdminPassword'

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.keyvault.outputs.acrAdminName }}
          password: ${{ steps.keyvault.outputs.acrAdminPassword }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:app-${{ github.run_number }}

  manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: Filippp96/k8s-demo-kubernetes
          token: ${{ secrets.GIT_TOKEN }}
          path: manifests

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s|tag: \".*\"|tag: \"app-${{ github.run_number }}\"|g" manifests/flaskdemo/values.yaml

      - name: Commit and push updated values.yaml
        working-directory: manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flaskdemo/values.yaml
          git commit -m "Update image tag to app-${{ github.run_number }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
