name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Retrieve secrets from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        id: keyvault
        with:
          keyvault: kv-k8s-demo-app-dev
          secrets: 'acrAdminName, acrAdminPassword'
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: acrk8sdemoappdev.azurecr.io
          username: ${{ steps.keyvault.outputs.acrAdminName }}
          password: ${{ steps.keyvault.outputs.acrAdminPassword }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: acrk8sdemoappdev.azurecr.io/images:app-${{ github.run_number }}
         
  manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: Filippp96/k8s-demo-kubernetes
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|acrk8sdemoappdev.azurecr.io/images:app-[0-9]\+|acrk8sdemoappdev.azurecr.io/images:app-${{ github.run_number }}|g" deployment.yaml
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update image tag to app-${{ github.run_number }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
